### ISSUE TITLE
PHPUnit tests for Collector class

### ISSUE THREAD

**Issue by xy2z** [xy2z/capro#23]
Make phpunit tests for all methods in the Collector class.

I already began a bit in `tests\CollectorTest.php`
You can see all methods that needs test in `src\Collector.php`

You can run the phpunit test by calling `vendor\bin\phpunit tests --testdox`

Please ask if you have any questions

---

🎃 For more PHP hacktoberfest issues, see:
https://github.com/search?q=owner%3Axy2z+label%3Ahacktoberfest+is%3Aopen&type=issues&s=comments&o=asc

**Comment by klezaic** [comment]
Hi,
please review the linked PR which implements the functionality required in this issue:
https://github.com/xy2z/capro/pull/26

Cheers
